apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app
            resources:
              limits:
                cpu: 4
                memory: 4Gi
              requests:
                cpu: 4
                memory: 4Gi
