apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app
            volumeMounts:
            - name: backups
              mountPath: /etc/backups
              subPath: postgres-backups
          volumes:
          - name: backups
            cephfs:
              readOnly: false
