apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: 0 4 * * *
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app
            env:
            - name: PG_BACKUP_DIR
              value: /etc/backups
            - name: PG_HOST
              value: postgres-svc.playground-dev.svc.cluster.local
            - name: PG_PORT
              value: "5432"
            - name: PG_USER
              value: example-dev
            - name: PG_PASSWORD
              value: example
            image: slamdev/playground-postgres-backupper
            resources:
              limits:
                cpu: 4
                memory: 4Gi
              requests:
                cpu: 4
                memory: 4Gi
            volumeMounts:
            - name: backups-volume
              mountPath: /etc/backups
              subPath: postgres-backups
          restartPolicy: OnFailure
          volumes:
          - name: backups-volume
            cephfs:
              path: /playground
              readOnly: false
              user: admin
              secretRef:
                name: ceph-secret
              monitors:
                - 10.10.10.1:6789
                - 10.10.10.2:6789
                - 10.10.10.3:6789
