apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app
            image: slamdev/playground-postgres-backupper
