apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app
            volumeMounts:
            - name: backups
              mountPath: /etc/backups
              subPath: postgres-backups
          volumes:
          - name: backups
            cephfs:
              monitors:
              - 10.10.10.1:6789
              - 10.10.10.2:6789
              - 10.10.10.3:6789
              user: admin
              path: /playground
              secretRef:
                name: ceph-secret
              readOnly: false
