apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: ClusterIP
  ports:
  - name: client
    port: 9200
    targetPort: client
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        ports:
        - name: client
          containerPort: 9200
        - name: transport
          containerPort: 9300
