apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
profiles:
- name: dev
  build:
    artifacts:
    - imageName: slamdev/playground-app1
      docker:
        dockerfilePath: deploy/Dockerfile
        cacheFrom:
        - nginx:alpine
        - slamdev/playground-app1:dev
  deploy:
    kustomize:
      kustomizePath: deploy/dev
- name: prod
  build:
    artifacts:
    - imageName: slamdev/playground-app1
      docker:
        dockerfilePath: deploy/Dockerfile
        cacheFrom:
        - nginx:alpine
        - slamdev/playground-app1:prod
  deploy:
    kustomize:
      kustomizePath: deploy/prod
- name: review
  build:
    artifacts:
    - imageName: slamdev/playground-app1
      docker:
        dockerfilePath: deploy/Dockerfile
        cacheFrom:
        - nginx:alpine
        - slamdev/playground-app1:review
  deploy:
    kubectl:
      manifests:
      - build/review-app.yaml
