apiVersion: skaffold/v1alpha2
kind: Config
profiles:
- name: dev
  deploy:
    kustomize:
      kustomizePath: deploy/dev
- name: prod
  deploy:
    kustomize:
      kustomizePath: deploy/prod
- name: review
  build:
    tagPolicy:
      sha256: {}
    artifacts:
    - imageName: slamdev/playground-postgres
      workspace: deploy/review/docker/postgres
      docker:
        cacheFrom:
        - postgres:9.6.9
        - slamdev/playground-postgres:review
    - imageName: slamdev/playground-postgres-restorer
      workspace: deploy/review/docker/postgres-restorer
      docker:
        cacheFrom:
        - alpine
        - slamdev/playground-postgres-restorer:review
  deploy:
    kubectl:
      manifests:
      - build/review-app.yaml
