apiVersion: skaffold/v1alpha2
kind: Config
profiles:
- name: dev
  deploy:
    kustomize:
      kustomizePath: k8s/overlays/dev
- name: prod
  deploy:
    kustomize:
      kustomizePath: k8s/overlays/prod
- name: review
  build:
    tagPolicy:
      sha256: {}
    artifacts:
    - imageName: slamdev/playground-postgres
      workspace: docker
  deploy:
    kubectl:
      manifests:
      - build/review-app.yaml
    kustomize: {}
