apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        resources:
          requests:
            memory: 4Gi
        env:
        - name: ES_JAVA_OPTS
          value: -Xms2000m -Xmx2000m
