apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
  artifacts:
  - imageName: slamdev/playground-builder-base
    workspace: builders/base
    docker:
      cacheFrom:
      - alpine
      - slamdev/playground-builder-base
  - imageName: slamdev/playground-builder-java
    workspace: builders/java
    docker:
      cacheFrom:
      - slamdev/playground-builder-base
      - slamdev/playground-builder-java
  - imageName: slamdev/playground-builder-js
    workspace: builders/js
    docker:
      cacheFrom:
      - slamdev/playground-builder-base
      - slamdev/playground-builder-js
  - imageName: slamdev/playground-dind
    workspace: dind
    docker:
      cacheFrom:
      - docker:dind
      - slamdev/playground-dind
  - imageName: slamdev/playground-gitlab-runner-helper
    workspace: gitlab-runner-helper
    docker:
      cacheFrom:
      - gitlab/gitlab-runner-helper:x86_64-latest
      - slamdev/playground-gitlab-runner-helper
deploy:
  kubectl: {}
