apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
spec:
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: app
        imagePullPolicy: Always
