.PHONY: clean
clean:
	@echo "etc-clean $(ENVIRONMENT)"

.PHONY: check
check:
	@echo "etc-check $(ENVIRONMENT)"

.PHONY: build
build:
	@echo "etc-build $(ENVIRONMENT)"

.PHONY: deploy
deploy:
	@echo "etc-deploy $(ENVIRONMENT)"
