apiVersion: skaffold/v1alpha2
kind: Config
profiles:
- name: dev
  deploy:
    kustomize:
      kustomizePath: deploy/dev
- name: prod
  deploy:
    kustomize:
      kustomizePath: deploy/prod
- name: review
  deploy:
    kubectl:
      manifests:
      - build/review-app.yaml
