apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: slamdev/playground-registry-ui
    workspace: deploy
    docker:
      cacheFrom:
      - quiq/docker-registry-ui:0.7.1
      - slamdev/playground-registry-ui:ops
deploy:
  kustomize:
    kustomizePath: deploy
