apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
      annotations:
        volume.beta.kubernetes.io/storage-class: hddpool
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template:
    spec:
      containers:
      - name: app
        volumeMounts:
        - name: backups
          mountPath: /etc/backups
          subPath: postgres-backups
      volumes:
      - name: backups
        cephfs:
          readOnly: false
