apiVersion: v1
kind: Service
metadata:
  name: governor-svc
spec:
  clusterIP: None
  ports:
  - name: transport
    port: 9300
    targetPort: transport
---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: ClusterIP
  ports:
  - name: client
    port: 9200
    targetPort: client
