apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: app
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
