apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: slamdev/playground-rabbitmq
    workspace: .
    docker:
      dockerfilePath: docker/Dockerfile
profiles:
- name: dev
  deploy:
    kustomize:
      kustomizePath: k8s/overlays/dev
- name: prod
  deploy:
    kustomize:
      kustomizePath: k8s/overlays/prod
- name: review
  deploy:
    kubectl:
      manifests:
      - build/review-app.yaml
    kustomize: {}
