.PHONY: clean
clean:
	@echo "ops-clean $(ENVIRONMENT)"

.PHONY: check
check:
	@echo "ops-check $(ENVIRONMENT)"

.PHONY: build
build:
	@echo "ops-build $(ENVIRONMENT)"

.PHONY: deploy
deploy:
	@echo "ops-deploy $(ENVIRONMENT)"
