resources:
- services.yaml
- stateful-set.yaml
- service-account.yaml
commonLabels:
  name: rabbitmq
namePrefix: rabbitmq-
configMapGenerator:
- name: config
  files:
  - rabbitmq.conf
  - enabled_plugins
