apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        volumeMounts:
        - mountPath: /etc/gitlab-runner
          name: configmap-volume
      initContainers:
      - name: registrator
        volumeMounts:
        - mountPath: /etc/gitlab-runner-root
          name: configmap-volume
        envFrom:
        - configMapRef:
            name: registration-config
      volumes:
      - name: configmap-volume
        configMap:
          name: config
      - name: registrator-config-volume
        configMap:
          name: registration-config
