resources:
- service-account.yaml
- deployment.yaml
commonLabels:
  name: gitlab-runner
  env: ops
namePrefix: gitlab-runner-
namespace: playground-ops
configMapGenerator:
- name: runner-config
  files:
  - config.toml
- name: registration-config
  literals:
  - PERSONAL_ACCESS_TOKENS=example
  - REGISTRATION_TOKEN=example
  - RUNNER_NAME=playground-runner
  - RUNNER_TAG_LIST=playground
  - CI_SERVER_URL=https://example.com
  - GITLAB_CONFIG_FILE=/etc/gitlab-runner-root/config.toml
